AllCops:
  Exclude:
    - 'bundle_bin/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FileName:
  Exclude:
    - exe/*

Style/RegexpLiteral:
  MaxSlashes: 0
